// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6omZvhjOSRKnlMQPfqRdSL_WADthHWGE',
    appId: '1:764127449010:web:000194dd2b138d29909eab',
    messagingSenderId: '764127449010',
    projectId: 'authify-3763a',
    authDomain: 'authify-3763a.firebaseapp.com',
    storageBucket: 'authify-3763a.firebasestorage.app',
    measurementId: 'G-366VDNLCTX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGoHAKiUPQudNX3UarbO1Z5Tr6h_XBGP8',
    appId: '1:764127449010:android:bf63abc54bf38d96909eab',
    messagingSenderId: '764127449010',
    projectId: 'authify-3763a',
    storageBucket: 'authify-3763a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaK7UHjMGCiWUeUFPtP64NGaVRrFoWKMY',
    appId: '1:764127449010:ios:0ca0721e4d064dce909eab',
    messagingSenderId: '764127449010',
    projectId: 'authify-3763a',
    storageBucket: 'authify-3763a.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthenticate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaK7UHjMGCiWUeUFPtP64NGaVRrFoWKMY',
    appId: '1:764127449010:ios:0ca0721e4d064dce909eab',
    messagingSenderId: '764127449010',
    projectId: 'authify-3763a',
    storageBucket: 'authify-3763a.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthenticate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6omZvhjOSRKnlMQPfqRdSL_WADthHWGE',
    appId: '1:764127449010:web:2fdfad227dffd8dd909eab',
    messagingSenderId: '764127449010',
    projectId: 'authify-3763a',
    authDomain: 'authify-3763a.firebaseapp.com',
    storageBucket: 'authify-3763a.firebasestorage.app',
    measurementId: 'G-C1STNXH011',
  );
}
